### ISSUE TITLE
Nothing copied to clipboard

### ISSUE THREAD

**Issue by musafarouk** [jasondonnette/sketch-copy-as-react-component#1]
I followed the instructions as stated in the Readme.MD file and the React Component wasn't copied to my clipboard.

**Comment by kevex91** [comment]
Same, copying SVG code the standard way works but this plugin hasn't worked for me either.

**Comment by jasondonnette** [comment]
Hey! Which version of Sketch are you guys on? Also, could you upload a sample of the file you are working with?

**Comment by kevex91** [comment]
Hey, I'm using Sketch 47.1 (45422).

This should link to the sketch file I was using: https://www.dropbox.com/s/uzsp3pigp6jeucm/icons.sketch?dl=0
